/*
* generated by Xtext
*/
package org.dadacoalition.ui.contentassist;

import org.dadacoalition.ui.contentassist.AbstractJsonProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JsonProposalProvider extends AbstractJsonProposalProvider {

}
