/*
 * generated by Xtext
 */
package org.dadacoalition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JsonUiModule extends org.dadacoalition.ui.AbstractJsonUiModule {
	public JsonUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
